CREATE TABLE REQUESTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    REQUESTER_ID INT NOT NULL,
    HELPER_ID INT NULL,
    DESIRED_DATE DATETIME NOT NULL,
    STATUS ENUM('ATTENTE', 'EN_COURS', 'REALISEE', 'ABANDONNEE', 'FERMEE') NOT NULL,
    KEYWORDS VARCHAR(255),
    FOREIGN KEY (REQUESTER_ID)
        REFERENCES STUDENTS (ID),
    FOREIGN KEY (HELPER_ID)
        REFERENCES STUDENTS (ID)
);
