CREATE TABLE REVIEWS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    REVIEW_TEXT TEXT,
    REVIEWER_ID INT NOT NULL,
    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENTS (ID)
    FOREIGN KEY (REVIEWER_ID)
        REFERENCES STUDENTS (ID)
);