CREATE TABLE STUDENTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(30),
    LASTNAME VARCHAR(30),
    EMAIL VARCHAR(30),
    ETABLISSEMENT VARCHAR(30),
    FILIERE VARCHAR(30),
    COMPETENCES VARCHAR(511),
    DISPONIBILITES VARCHAR(511),
    AVIS VARCHAR(511)
);